resolver: lts-5.14
packages:
- '.'
extra-deps:
- control-monad-omega-0.3.1
- servant-0.7
- servant-blaze-0.7
- servant-client-0.7
- servant-docs-0.7
- servant-foreign-0.7
- servant-js-0.7
- servant-lucid-0.7
- servant-server-0.7
